### ISSUE TITLE
move_base build error

### ISSUE THREAD

**Issue by cinchcircuits** [mayfieldrobotics/navigation#31]
Seen during build of deb

ie: bloom-generate rosdebian --os-name ubuntu --os-version trusty --ros-distro indigo; fakeroot debian/rules binary

/root/gizmo/src/navigation/move_base/src/move_base.cpp: In member function 'bool move_base::MoveBase::executeCycle(geometry_msgs::PoseStamped&, std::vector<geometry_msgs::PoseStamped_<std::allocator<void> > >&)':
/root/gizmo/src/navigation/move_base/src/move_base.cpp:960:19: error: 'class nav_core::BaseLocalPlanner' has no member named 'isRotatingToGoal'
           if(tc_->isRotatingToGoal()){
                   ^
make[4]: *** [CMakeFiles/move_base.dir/src/move_base.cpp.o] Error 1

Known error?

**Comment by KaijenHsiao** [comment]
Not known error.  What exactly is being compiled?  move_base compiles just fine in our normal catkin_make... the function in question can be seen here:
https://github.com/mayfieldrobotics/navigation/blob/develop/nav_core/include/nav_core/base_local_planner.h#L69

**Comment by cinchcircuits** [comment]
It appears that this is appearing when catkin is trying to build move_base.cpp

/usr/bin/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"move_base\" -Dmove_base_EXPORTS -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -D_FORTIFY_SOURCE=2  -fPIC -I/root/embedded-ansible/navigation/move_base/obj-x86_64-linux-gnu/devel/include -I/root/embedded-ansible/navigation/move_base/include -I/opt/ros/indigo/include -I/usr/include/eigen3 -I/usr/include/pcl-1.7 -I/usr/include/ni -I/usr/include/vtk-5.8    -o CMakeFiles/move_base.dir/src/move_base.cpp.o -c /root/embedded-ansible/navigation/move_base/src/move_base.cpp

I do not see where this catkin make pull in nav core. That's likley the problem. Will investigate a bit more later.

**Comment by cinchcircuits** [comment]
Build error no longer appears to happen
