### ISSUE TITLE
class nav_core::BaseLocalPlanner' has no member named 'isRotatingToGoal' build error

### ISSUE THREAD

**Issue by cinchcircuits** [mayfieldrobotics/navigation#32]
seems new. 

To reproduce:

clone repo

cd to navigation/move_base

pip install bloom
bloom-generate rosdebian --os-name ubuntu --os-version trusty --ros-distro indigo
fakeroot debian/rules binary

/usr/bin/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"move_base\" -Dmove_base_EXPORTS -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -D_FORTIFY_SOURCE=2  -fPIC -I/root/embedded-ansible/navigation/move_base/obj-arm-linux-gnueabihf/devel/include -I/root/embedded-ansible/navigation/move_base/include -I/opt/ros/indigo/include -I/usr/include/eigen3 -I/usr/include/pcl-1.7 -I/usr/include/ni -I/usr/include/vtk-5.8    -o CMakeFiles/move_base.dir/src/move_base.cpp.o -c /root/embedded-ansible/navigation/move_base/src/move_base.cpp
/root/embedded-ansible/navigation/move_base/src/move_base.cpp: In member function 'bool move_base::MoveBase::executeCycle(geometry_msgs::PoseStamped&, std::vector<geometry_msgs::PoseStamped_<std::allocator<void> > >&)':
/root/embedded-ansible/navigation/move_base/src/move_base.cpp:858:15: error: 'move_base_msgs::MoveBaseFeedback' has no member named 'state'
      feedback.state = "clearing";
               ^
/root/embedded-ansible/navigation/move_base/src/move_base.cpp:861:15: error: 'move_base_msgs::MoveBaseFeedback' has no member named 'state'
      feedback.state = "planning";
               ^
/root/embedded-ansible/navigation/move_base/src/move_base.cpp:864:15: error: 'move_base_msgs::MoveBaseFeedback' has no member named 'state'
      feedback.state = "controlling";
               ^
/root/embedded-ansible/navigation/move_base/src/move_base.cpp:974:19: error: 'class nav_core::BaseLocalPlanner' has no member named 'isRotatingToGoal'
           if(tc_->isRotatingToGoal()){
                   ^
^[[Cmake[4]: **\* [CMakeFiles/move_base.dir/src/move_base.cpp.o] Error 1

**Comment by jonbinney** [comment]
The first few errors are about a missing "state" field in the feedback message. That field was added to mayfield's fork of the nav stack in this commit: https://github.com/mayfieldrobotics/navigation/commit/0bd8985a0e62efcac91608604a42cf6ec639361b

Is it possible you're building the mayfield fork version of move_base with the main ros version of move_base_msgs?

**Comment by cinchcircuits** [comment]
That was the problem Jon. I had the ros version of move_base_msgs and indigo_nav_core. 

Building and installing the mayfield versions seems to fix the problem. 

I'll have to come up with a creative way to fix this problem. I may need to make the mayfield version a higher version that is the willow version as running "rosdep install -y -i --from-path ." seems to pick up the main ros version,
